PAC.WebApplication/Models/ErrorViewModel.cs
using System;

namespace PAC.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PAC.WebApplication/Models/VehiculoModel.cs
using PAC.Business.Contracts;

namespace PAC.WebApplication.Models
{
    public class VehiculoModel
    {
        public VehiculoResponse VehiculoResponse { get; set; }
    }
}

PAC.WebApplication/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PAC.Business.Contracts;
using PAC.Entities;
using PAC.WebApplication.Models;

namespace PAC.WebApplication.Controllers
{

    public class VehiculoController : Controller
    {
        //TODO: mover para appsettings
        const string BASE_URL = "http://localhost:57524/";

        public async Task<IActionResult> Index()
        {
            var list = new List<Vehiculo>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(BASE_URL);

                //Define request data format  
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.Timeout = TimeSpan.FromSeconds(60);

                //Sending request to find web api REST service resource GetAll using HttpClient  
                HttpResponseMessage response = await client.GetAsync("api/v1/vehiculo");

                //Checking the response is successful or not which is sent using HttpClient  
                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var stringResponse = response.Content.ReadAsStringAsync().Result;
                    //Deserializing the response recieved from web api and storing into the list  
                    list = JsonConvert.DeserializeObject<List<Vehiculo>>(stringResponse);
                }
                //returning the list to view  
                return View(list);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var vehiculo = new Vehiculo();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(BASE_URL);

                //Define request data format  
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.Timeout = TimeSpan.FromSeconds(60);

                //Sending request to find web api REST service resource GetAll using HttpClient  
                HttpResponseMessage response = await client.GetAsync($"api/v1/vehiculo/{id}");

                //Checking the response is successful or not which is sent using HttpClient  
                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var stringResponse = response.Content.ReadAsStringAsync().Result;
                    if (stringResponse != string.Empty) {
                        //Deserializing the response recieved from web api and storing into the list  
                        vehiculo = JsonConvert.DeserializeObject<Vehiculo>(stringResponse);
                    }
                }
                //returning the item to view  
                return View(vehiculo);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm]Vehiculo vehiculo)
        {
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(BASE_URL);

                //Define request data format  
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.Timeout = TimeSpan.FromSeconds(60);

                //Sending request to find web api REST service resource GetAll using HttpClient  
                HttpResponseMessage response = await client.PostAsJsonAsync($"api/v1/vehiculo", vehiculo);

                //Checking the response is successful or not which is sent using HttpClient  
                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var stringResponse = response.Content.ReadAsStringAsync().Result;
                    if (stringResponse != string.Empty)
                    {
                        //Deserializing the response recieved from web api and storing into the list  
                        vehiculo = JsonConvert.DeserializeObject<Vehiculo>(stringResponse);
                    }
                }
                //returning to list  
                return RedirectToAction("Index");
                //return View(vehiculo);
            }
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Vehiculo vehiculo)
        {
           
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(BASE_URL);

                //Define request data format  
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.Timeout = TimeSpan.FromSeconds(60);

                //Sending request to find web api REST service resource GetAll using HttpClient  
                var vehiculoRequest = new VehiculoRequest { IdVehiculo = vehiculo.IdVehiculo, NumeroOrden = vehiculo.NumeroOrden, Placa = vehiculo.Placa };
                HttpResponseMessage response = await client.PutAsJsonAsync($"api/v1/vehiculo", vehiculoRequest);

                //Checking the response is successful or not which is sent using HttpClient  
                if (response.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var stringResponse = response.Content.ReadAsStringAsync().Result;
                    if (stringResponse != string.Empty)
                    {
                        //Deserializing the response recieved from web api and storing into the list  
                        vehiculo = JsonConvert.DeserializeObject<Vehiculo>(stringResponse);
                    }
                }
                //returning to list  
                return RedirectToAction("Index");
                //return View(vehiculo);
            }

        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PAC.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAC.WebApplication</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Vehiculo" asp-action="Index" class="navbar-brand">PAC.WebApplication</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Vehiculo" asp-action="Index">Vehículos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - PAC.WebApplication</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

PAC.WebApplication/Views/Vehiculo/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

PAC.WebApplication/Views/Vehiculo/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PAC.WebApplication/Views/Vehiculo/Create.cshtml
@model PAC.Entities.Vehiculo

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Vehículo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdVehiculo" />
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" />
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroOrden" class="control-label"></label>
                <input asp-for="NumeroOrden" class="form-control" />
                <span asp-validation-for="NumeroOrden" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PAC.WebApplication/Views/Vehiculo/Edit.cshtml
@model PAC.Entities.Vehiculo

@{
    ViewData["Title"] = "Edit";
}

<h2>Vehículo</h2>

<h4>Editar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdVehiculo" />

            <div class="form-group">
                <label asp-for="Placa" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Placa" class="form-control" />
                    <span asp-validation-for="Placa" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="NumeroOrden" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="NumeroOrden" class="form-control" />
                    <span asp-validation-for="NumeroOrden" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PAC.WebApplication/Views/Vehiculo/Index.cshtml
@model List<PAC.Entities.Vehiculo>

@{
    ViewData["Title"] = "Index";
}


<h2>Vehículos</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Placa</th>
            <th>Acciones</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Placa
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdVehiculo">Editar</a> |
                    @Html.ActionLink("Edit", "Edit", new { id = item.IdVehiculo }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

PAC.WebApplication/Views/Vehiculo/View.cshtml
@model PAC.WebApplication.Models.VehiculoModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Placa</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.VehiculoResponse.Vehiculos) {
        <tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>